# dev-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-app
  region: us-east-1
  version: '1.31'
  tags:
    karpenter.sh/discovery: demo-app

iam:
  withOIDC: true # required
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: "kube-system"
    roleName: demo-app-karpenter
    attachPolicyARNs:
    - arn:aws:iam::757641753030:policy/KarpenterControllerPolicy-demo-app
    roleOnly: true

iamIdentityMappings:
- arn: "arn:aws:iam::757641753030:role/KarpenterNodeRole-demo-app"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes
  ## If you intend to run Windows workloads, the kube-proxy group should be specified.
  # For more information, see https://github.com/aws/karpenter/issues/5099.
  # - eks:kube-proxy-windows

addons:
  - name: eks-pod-identity-agent
    tags:
      team: heinux
      environment: demo
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: aws-load-balancer-controller
    version: latest

fargateProfiles:
  - name: karpenter
    selectors:
      # All workloads in the "kube-system" Kubernetes namespace will be scheduled onto Fargate:
      - namespace: kube-system