# dev-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: development-cluster
  region: us-east-1
  version: '1.31'
  tags:
    karpenter.sh/discovery: development-cluster

iam:
  withOIDC: true # required
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: "karpenter"
    roleName: development-cluster-karpenter-role
    attachPolicyARNs:
    - arn:aws:iam::757641753030:policy/KarpenterControllerPolicy-development-cluster
    roleOnly: false

addons:
  - name: eks-pod-identity-agent # required for `iam.podIdentityAssociations`
    tags:
      team: heinux
      environment: development
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "karpenter" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: karpenter
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system