apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-action-runner
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: Heinux-Training
      labels:
        - "demo-app"
        - "heinux"
        - "self-hosted"
        - "development"
      group: "Development"