apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: eks-runner-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: k8s-action-runner
    kind: RunnerDeployment
  minReplicas: 0
  maxReplicas: 10
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "20m"