alertmanager:
  enabled: false
  persistentVolume:
    enabled: false

server:
  fullnameOverride: prometheus-server
  persistentVolume:
    enabled: false

# Exclude Fargate nodes for node exporter
prometheus-node-exporter:
  
  # affinity: 
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchFields:
  #             - key: metadata.name
  #               operator: In
  #               values:
  #                 - target-host-name
  nodeSelector:
    karpenter.sh/initialized: "true"

extraScrapeConfigs: |
    - job_name: karpenter
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - kube-system
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_endpoints_name
        - __meta_kubernetes_endpoint_port_name
        action: keep
        regex: karpenter;http-metrics
